
#General mod settings
[general]
	#Takes the sand out of sandwiches
	Storm_NoSandstorms = false
	#-
	Sandstorm_UseGlobalServerRate = false
	#-
	#Range: > 0
	Sandstorm_OddsTo1 = 30
	#Time between sandstorms for either each player or entire server depending on if global rate is on, default: 3 client days
	#Range: > 0
	Sandstorm_TimeBetweenInTicks = 72000
	#Amount of game ticks between sand buildup iterations, keep it high to prevent client side chunk tick spam that destroys FPS
	#Range: > 0
	Sandstorm_Sand_Buildup_TickRate = 40
	#Base amount of loops done per iteration, scaled by the sandstorms intensity (value given here is the max possible)
	#Range: > 0
	Sandstorm_Sand_Buildup_LoopAmountBase = 800
	#Max height of sand allowed to buildup against something, higher = things get more buried over time
	#Range: > 0
	Sandstorm_Sand_Block_Max_Height = 3
	#Allow layered sand blocks to buildup outside deserty biomes where sandstorm is
	Sandstorm_Sand_Buildup_AllowOutsideDesert = true
	#-
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Sandstorm_Particle_Dust_effect_rate = 0.6
	#-
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Sandstorm_Particle_Debris_effect_rate = 0.6
	#-
	Sandstorm_Siren_PleaseNoDarude = false

