
#General mod settings
[general]
	#-
	Misc_windOn = true
	#-
	Wind_LowWindEvents = true
	#-
	Wind_HighWindEvents = true
	#-
	Wind_UsePerlinNoise = false
	#-
	#Range: > 0
	lowWindTimerEnableAmountBase = 2400
	#-
	#Range: > 0
	lowWindTimerEnableAmountRnd = 12000
	#-
	#Range: > 0
	lowWindOddsTo1 = 4000
	#-
	#Range: > 0
	highWindTimerEnableAmountBase = 2400
	#-
	#Range: > 0
	highWindTimerEnableAmountRnd = 12000
	#-
	#Range: > 0
	highWindOddsTo1 = 8000
	#-
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	globalWindAngleChangeAmountRate = 1.0
	#-
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	windSpeedMin = 1.0E-5
	#-
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	windSpeedMax = 1.0
	#Min wind speed to maintain if its raining with global overcast mode on, overrides low wind events and windSpeedMin
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	windSpeedMinGlobalOvercastRaining = 0.01
	#-
	#Range: > 0
	Wind_Turbine_FE_Generated_Per_Tick = 10

