
[general]
	#
	# Max animal size that the animal cart can carry.
	#Range: 0 ~ 69
	maxAnimalSize = 3
	#
	# The largest (inclusive) size of an item that is allowed in a supply cart.
	#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
	maxItemSize = "VERY_LARGE"
	#
	# Can the animal cart pick up players by pushing it into them?
	canPushIntoPlayers = true
	#
	# Can the animal cart pick up water animals?
	canCarryWaterEntities = true

