
[display]
	#If false, only the effects of aged alcohol will be shown on fluid container items like jugs and buckets.
	#Otherwise, effects like Thirst for Salt Water Ceramic Jug will also be shown
	showEffectTooltipForAllDrinkables = false

